version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/pinspot
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
volumes:
  postgres_volume:
